/*
 * CutMeShort CMS API
 * Official API for the CutMeShort CMS platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.cutmeshort.client.auth;

import java.io.Serializable;
import java.util.Arrays;
import com.cutmeshort.client.util.AppConstants;

/**
 * Secure API Key Manager
 *
 * This class provides secure handling of API credentials with the following features:
 * - Immutable design to prevent accidental modifications
 * - Secure string storage using char arrays instead of String objects
 * - Automatic memory cleanup
 * - Prevents logging/toString exposure of sensitive data
 * - Thread-safe access to credentials
 *
 * <h2>Usage Example</h2>
 * <pre>
 * // Load from environment
 * SecureApiKeyManager keyManager = SecureApiKeyManager.fromEnvironment();
 *
 * // Or create directly
 * char[] apiKeyChars = "your-api-key".toCharArray();
 * SecureApiKeyManager keyManager = new SecureApiKeyManager(apiKeyChars);
 *
 * // Use in ApiClient
 * ApiClient client = new ApiClient();
 * client.setSecureApiKey(keyManager);
 *
 * // Keys are automatically cleared when manager is garbage collected
 * </pre>
 *
 * @see AppConstants#getApiKey()
 * @see SecureString
 */
public final class SecureApiKeyManager implements Serializable {

    private static final long serialVersionUID = 1L;

    // Immutable secure storage
    private final SecureString apiKey;
    private final SecureString apiKeyPrefix;

    /**
     * Create a manager with an API key as char array
     * The char array is copied internally and should be cleared by the caller
     *
     * @param apiKeyChars API key as char array (will be copied, not stored directly)
     * @throws IllegalArgumentException if apiKeyChars is null or empty
     */
    public SecureApiKeyManager(char[] apiKeyChars) {
        this(apiKeyChars, null);
    }

    /**
     * Create a manager with an API key and optional prefix
     *
     * @param apiKeyChars API key as char array
     * @param prefixChars Optional prefix (e.g., "Bearer ") as char array
     * @throws IllegalArgumentException if apiKeyChars is null or empty
     */
    public SecureApiKeyManager(char[] apiKeyChars, char[] prefixChars) {
        if (apiKeyChars == null || apiKeyChars.length == 0) {
            throw new IllegalArgumentException("API key cannot be null or empty");
        }

        // Store in secure wrappers (copies the data)
        this.apiKey = new SecureString(apiKeyChars);
        this.apiKeyPrefix = prefixChars != null ? new SecureString(prefixChars) : null;
    }

    /**
     * Load API key from environment variables securely
     *
     * @return SecureApiKeyManager loaded from environment
     * @throws IllegalStateException if API key is not configured
     */
    public static SecureApiKeyManager fromEnvironment() {
        String apiKeyStr = AppConstants.getApiKey();

        if (apiKeyStr == null || apiKeyStr.isEmpty()) {
            throw new IllegalStateException(AppConstants.ERROR_API_KEY_NOT_CONFIGURED);
        }

        // Convert String to char array and immediately create manager
        char[] keyChars = apiKeyStr.toCharArray();
        try {
            return new SecureApiKeyManager(keyChars);
        } finally {
            // Clear the temporary char array
            Arrays.fill(keyChars, '\0');
        }
    }

    /**
     * Get the API key as a String
     * WARNING: String objects are immutable and may persist in memory.
     * Use getApiKeyAsCharArray() when possible for sensitive operations.
     *
     * @return API key as String
     */
    public synchronized String getApiKey() {
        return apiKey.getString();
    }

    /**
     * Get the API key as a char array
     * IMPORTANT: Caller MUST clear this array after use with Arrays.fill()
     *
     * @return API key as char array (must be cleared by caller)
     */
    public synchronized char[] getApiKeyAsCharArray() {
        return apiKey.getCharArray().clone();
    }

    /**
     * Get the API key prefix (e.g., "Bearer ") as a String if set
     *
     * @return API key prefix or null if not set
     */
    public synchronized String getApiKeyPrefix() {
        return apiKeyPrefix != null ? apiKeyPrefix.getString() : null;
    }

    /**
     * Get the full authorization value (prefix + key)
     * Returns "{prefix}{key}" or just "{key}" if no prefix
     *
     * @return Full authorization value
     */
    public synchronized String getFullAuthValue() {
        String prefix = getApiKeyPrefix();
        String key = getApiKey();

        if (prefix != null && !prefix.isEmpty()) {
            return prefix + key;
        }
        return key;
    }

    /**
     * Check if API key is configured
     *
     * @return true if API key is set
     */
    public synchronized boolean isConfigured() {
        return apiKey != null;
    }

    /**
     * Clear all sensitive data from memory
     * This should be called when the manager is no longer needed
     * Note: This is called automatically by the finalizer, but explicit call is recommended
     */
    public synchronized void clear() {
        if (apiKey != null) {
            apiKey.clear();
        }
        if (apiKeyPrefix != null) {
            apiKeyPrefix.clear();
        }
    }

    /**
     * NEVER expose the API key in toString()
     * Returns a safe representation that doesn't leak credentials
     */
    @Override
    public String toString() {
        return "SecureApiKeyManager{" +
            "apiKey=" + (apiKey != null ? "***REDACTED***" : "null") +
            ", hasPrefix=" + (apiKeyPrefix != null) +
            '}';
    }

    /**
     * Prevents hashCode/equals from relying on sensitive data
     */
    @Override
    public int hashCode() {
        // Use object identity only
        return System.identityHashCode(this);
    }

    /**
     * Prevents comparison that might leak information
     */
    @Override
    public boolean equals(Object obj) {
        // Only equal to itself
        return this == obj;
    }

    /**
     * Cleanup on garbage collection
     */
    @Override
    protected void finalize() throws Throwable {
        try {
            clear();
        } finally {
            super.finalize();
        }
    }

    // ============================================================================
    // INNER CLASS: SecureString
    // ============================================================================

    /**
     * Internal class for secure string storage
     * Stores data as chars instead of String to allow memory overwriting
     */
    private static final class SecureString {
        private final char[] chars;

        /**
         * Create a SecureString by copying the input char array
         */
        SecureString(char[] input) {
            if (input == null || input.length == 0) {
                throw new IllegalArgumentException("Input cannot be null or empty");
            }
            this.chars = input.clone();
        }

        /**
         * Get the content as a String
         * Note: The returned String may persist in memory
         */
        synchronized String getString() {
            if (chars == null) {
                return null;
            }
            return new String(chars);
        }

        /**
         * Get the content as a char array copy
         * Caller must clear the returned array
         */
        synchronized char[] getCharArray() {
            if (chars == null) {
                return null;
            }
            return chars.clone();
        }

        /**
         * Clear the sensitive data from memory
         */
        synchronized void clear() {
            if (chars != null) {
                Arrays.fill(chars, '\0');
            }
        }

        @Override
        public String toString() {
            return "***REDACTED***";
        }

        @Override
        protected void finalize() throws Throwable {
            try {
                clear();
            } finally {
                super.finalize();
            }
        }
    }
}
