/*
 * CutMeShort CMS API
 * Official API for the CutMeShort CMS platform.  This API allows tracking of leads and sales, including deferred lead attribution. In deferred attribution, the first lead call stores the clickId-to-customerExternalId association using `mode: deferred`. Subsequent lead events should be sent as normal events without `mode`, and the backend resolves the stored association automatically. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cutmeshort.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.cutmeshort.client.util.JSON;

/**
 * LeadPayload
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-20T11:35:18.165374+05:30[Asia/Kolkata]", comments = "Generator version: 7.20.0")
public class LeadPayload {
  public static final String SERIALIZED_NAME_CLICK_ID = "clickId";
  @SerializedName(SERIALIZED_NAME_CLICK_ID)
  @javax.annotation.Nullable
  private String clickId;

  public static final String SERIALIZED_NAME_EVENT_NAME = "eventName";
  @SerializedName(SERIALIZED_NAME_EVENT_NAME)
  @javax.annotation.Nonnull
  private String eventName;

  public static final String SERIALIZED_NAME_CUSTOMER_EXTERNAL_ID = "customerExternalId";
  @SerializedName(SERIALIZED_NAME_CUSTOMER_EXTERNAL_ID)
  @javax.annotation.Nonnull
  private String customerExternalId;

  public static final String SERIALIZED_NAME_TIMESTAMP = "timestamp";
  @SerializedName(SERIALIZED_NAME_TIMESTAMP)
  @javax.annotation.Nullable
  private OffsetDateTime timestamp;

  public static final String SERIALIZED_NAME_CUSTOMER_NAME = "customerName";
  @SerializedName(SERIALIZED_NAME_CUSTOMER_NAME)
  @javax.annotation.Nullable
  private String customerName;

  public static final String SERIALIZED_NAME_CUSTOMER_EMAIL = "customerEmail";
  @SerializedName(SERIALIZED_NAME_CUSTOMER_EMAIL)
  @javax.annotation.Nullable
  private String customerEmail;

  public static final String SERIALIZED_NAME_CUSTOMER_AVATAR = "customerAvatar";
  @SerializedName(SERIALIZED_NAME_CUSTOMER_AVATAR)
  @javax.annotation.Nullable
  private URI customerAvatar;

  /**
   * Use &#x60;deferred&#x60; only when creating the deferred clickId-to-customerExternalId association. Subsequent lead events should omit this field. 
   */
  @JsonAdapter(ModeEnum.Adapter.class)
  public enum ModeEnum {
    DEFERRED("deferred");

    private String value;

    ModeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ModeEnum fromValue(String value) {
      for (ModeEnum b : ModeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ModeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ModeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ModeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ModeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      ModeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_MODE = "mode";
  @SerializedName(SERIALIZED_NAME_MODE)
  @javax.annotation.Nullable
  private ModeEnum mode;

  public LeadPayload() {
  }

  public LeadPayload clickId(@javax.annotation.Nullable String clickId) {
    this.clickId = clickId;
    return this;
  }

  /**
   * Required for standard lead tracking and for deferred association setup. May be omitted for later normal lead events if a prior deferred association already exists for the given customerExternalId. 
   * @return clickId
   */
  @javax.annotation.Nullable
  public String getClickId() {
    return clickId;
  }

  public void setClickId(@javax.annotation.Nullable String clickId) {
    this.clickId = clickId;
  }


  public LeadPayload eventName(@javax.annotation.Nonnull String eventName) {
    this.eventName = eventName;
    return this;
  }

  /**
   * Name of the lead event.
   * @return eventName
   */
  @javax.annotation.Nonnull
  public String getEventName() {
    return eventName;
  }

  public void setEventName(@javax.annotation.Nonnull String eventName) {
    this.eventName = eventName;
  }


  public LeadPayload customerExternalId(@javax.annotation.Nonnull String customerExternalId) {
    this.customerExternalId = customerExternalId;
    return this;
  }

  /**
   * Your unique external identifier for the customer.
   * @return customerExternalId
   */
  @javax.annotation.Nonnull
  public String getCustomerExternalId() {
    return customerExternalId;
  }

  public void setCustomerExternalId(@javax.annotation.Nonnull String customerExternalId) {
    this.customerExternalId = customerExternalId;
  }


  public LeadPayload timestamp(@javax.annotation.Nullable OffsetDateTime timestamp) {
    this.timestamp = timestamp;
    return this;
  }

  /**
   * ISO 8601 timestamp.
   * @return timestamp
   */
  @javax.annotation.Nullable
  public OffsetDateTime getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(@javax.annotation.Nullable OffsetDateTime timestamp) {
    this.timestamp = timestamp;
  }


  public LeadPayload customerName(@javax.annotation.Nullable String customerName) {
    this.customerName = customerName;
    return this;
  }

  /**
   * Get customerName
   * @return customerName
   */
  @javax.annotation.Nullable
  public String getCustomerName() {
    return customerName;
  }

  public void setCustomerName(@javax.annotation.Nullable String customerName) {
    this.customerName = customerName;
  }


  public LeadPayload customerEmail(@javax.annotation.Nullable String customerEmail) {
    this.customerEmail = customerEmail;
    return this;
  }

  /**
   * Get customerEmail
   * @return customerEmail
   */
  @javax.annotation.Nullable
  public String getCustomerEmail() {
    return customerEmail;
  }

  public void setCustomerEmail(@javax.annotation.Nullable String customerEmail) {
    this.customerEmail = customerEmail;
  }


  public LeadPayload customerAvatar(@javax.annotation.Nullable URI customerAvatar) {
    this.customerAvatar = customerAvatar;
    return this;
  }

  /**
   * Get customerAvatar
   * @return customerAvatar
   */
  @javax.annotation.Nullable
  public URI getCustomerAvatar() {
    return customerAvatar;
  }

  public void setCustomerAvatar(@javax.annotation.Nullable URI customerAvatar) {
    this.customerAvatar = customerAvatar;
  }


  public LeadPayload mode(@javax.annotation.Nullable ModeEnum mode) {
    this.mode = mode;
    return this;
  }

  /**
   * Use &#x60;deferred&#x60; only when creating the deferred clickId-to-customerExternalId association. Subsequent lead events should omit this field. 
   * @return mode
   */
  @javax.annotation.Nullable
  public ModeEnum getMode() {
    return mode;
  }

  public void setMode(@javax.annotation.Nullable ModeEnum mode) {
    this.mode = mode;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LeadPayload leadPayload = (LeadPayload) o;
    return Objects.equals(this.clickId, leadPayload.clickId) &&
        Objects.equals(this.eventName, leadPayload.eventName) &&
        Objects.equals(this.customerExternalId, leadPayload.customerExternalId) &&
        Objects.equals(this.timestamp, leadPayload.timestamp) &&
        Objects.equals(this.customerName, leadPayload.customerName) &&
        Objects.equals(this.customerEmail, leadPayload.customerEmail) &&
        Objects.equals(this.customerAvatar, leadPayload.customerAvatar) &&
        Objects.equals(this.mode, leadPayload.mode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clickId, eventName, customerExternalId, timestamp, customerName, customerEmail, customerAvatar, mode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LeadPayload {\n");
    sb.append("    clickId: ").append(toIndentedString(clickId)).append("\n");
    sb.append("    eventName: ").append(toIndentedString(eventName)).append("\n");
    sb.append("    customerExternalId: ").append(toIndentedString(customerExternalId)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    customerName: ").append(toIndentedString(customerName)).append("\n");
    sb.append("    customerEmail: ").append(toIndentedString(customerEmail)).append("\n");
    sb.append("    customerAvatar: ").append(toIndentedString(customerAvatar)).append("\n");
    sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("clickId", "eventName", "customerExternalId", "timestamp", "customerName", "customerEmail", "customerAvatar", "mode"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("eventName", "customerExternalId"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to LeadPayload
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!LeadPayload.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in LeadPayload is not found in the empty JSON string", LeadPayload.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!LeadPayload.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `LeadPayload` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : LeadPayload.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("clickId") != null && !jsonObj.get("clickId").isJsonNull()) && !jsonObj.get("clickId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `clickId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("clickId").toString()));
      }
      if (!jsonObj.get("eventName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `eventName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("eventName").toString()));
      }
      if (!jsonObj.get("customerExternalId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `customerExternalId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("customerExternalId").toString()));
      }
      if ((jsonObj.get("customerName") != null && !jsonObj.get("customerName").isJsonNull()) && !jsonObj.get("customerName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `customerName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("customerName").toString()));
      }
      if ((jsonObj.get("customerEmail") != null && !jsonObj.get("customerEmail").isJsonNull()) && !jsonObj.get("customerEmail").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `customerEmail` to be a primitive type in the JSON string but got `%s`", jsonObj.get("customerEmail").toString()));
      }
      if ((jsonObj.get("customerAvatar") != null && !jsonObj.get("customerAvatar").isJsonNull()) && !jsonObj.get("customerAvatar").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `customerAvatar` to be a primitive type in the JSON string but got `%s`", jsonObj.get("customerAvatar").toString()));
      }
      if ((jsonObj.get("mode") != null && !jsonObj.get("mode").isJsonNull()) && !jsonObj.get("mode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `mode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("mode").toString()));
      }
      // validate the optional field `mode`
      if (jsonObj.get("mode") != null && !jsonObj.get("mode").isJsonNull()) {
        ModeEnum.validateJsonElement(jsonObj.get("mode"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!LeadPayload.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'LeadPayload' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<LeadPayload> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(LeadPayload.class));

       return (TypeAdapter<T>) new TypeAdapter<LeadPayload>() {
           @Override
           public void write(JsonWriter out, LeadPayload value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public LeadPayload read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of LeadPayload given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of LeadPayload
   * @throws IOException if the JSON string is invalid with respect to LeadPayload
   */
  public static LeadPayload fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, LeadPayload.class);
  }

  /**
   * Convert an instance of LeadPayload to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

