/*
 * CutMeShort CMS API
 * Official API for the CutMeShort CMS platform.  This API allows tracking of leads and sales, including deferred lead attribution. In deferred attribution, the first lead call stores the clickId-to-customerExternalId association using `mode: deferred`. Subsequent lead events should be sent as normal events without `mode`, and the backend resolves the stored association automatically. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cutmeshort.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.cutmeshort.client.util.JSON;

/**
 * SalePayload
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-20T11:35:18.165374+05:30[Asia/Kolkata]", comments = "Generator version: 7.20.0")
public class SalePayload {
  public static final String SERIALIZED_NAME_CLICK_ID = "clickId";
  @SerializedName(SERIALIZED_NAME_CLICK_ID)
  @javax.annotation.Nonnull
  private String clickId;

  public static final String SERIALIZED_NAME_EVENT_NAME = "eventName";
  @SerializedName(SERIALIZED_NAME_EVENT_NAME)
  @javax.annotation.Nonnull
  private String eventName;

  public static final String SERIALIZED_NAME_TIMESTAMP = "timestamp";
  @SerializedName(SERIALIZED_NAME_TIMESTAMP)
  @javax.annotation.Nullable
  private OffsetDateTime timestamp;

  public static final String SERIALIZED_NAME_CUSTOMER_EXTERNAL_ID = "customerExternalId";
  @SerializedName(SERIALIZED_NAME_CUSTOMER_EXTERNAL_ID)
  @javax.annotation.Nonnull
  private String customerExternalId;

  public static final String SERIALIZED_NAME_CUSTOMER_NAME = "customerName";
  @SerializedName(SERIALIZED_NAME_CUSTOMER_NAME)
  @javax.annotation.Nullable
  private String customerName;

  public static final String SERIALIZED_NAME_CUSTOMER_EMAIL = "customerEmail";
  @SerializedName(SERIALIZED_NAME_CUSTOMER_EMAIL)
  @javax.annotation.Nullable
  private String customerEmail;

  public static final String SERIALIZED_NAME_CUSTOMER_AVATAR = "customerAvatar";
  @SerializedName(SERIALIZED_NAME_CUSTOMER_AVATAR)
  @javax.annotation.Nullable
  private URI customerAvatar;

  public static final String SERIALIZED_NAME_INVOICE_ID = "invoiceId";
  @SerializedName(SERIALIZED_NAME_INVOICE_ID)
  @javax.annotation.Nonnull
  private String invoiceId;

  public static final String SERIALIZED_NAME_AMOUNT = "amount";
  @SerializedName(SERIALIZED_NAME_AMOUNT)
  @javax.annotation.Nonnull
  private Double amount;

  public static final String SERIALIZED_NAME_CURRENCY = "currency";
  @SerializedName(SERIALIZED_NAME_CURRENCY)
  @javax.annotation.Nonnull
  private String currency;

  public SalePayload() {
  }

  public SalePayload clickId(@javax.annotation.Nonnull String clickId) {
    this.clickId = clickId;
    return this;
  }

  /**
   * Get clickId
   * @return clickId
   */
  @javax.annotation.Nonnull
  public String getClickId() {
    return clickId;
  }

  public void setClickId(@javax.annotation.Nonnull String clickId) {
    this.clickId = clickId;
  }


  public SalePayload eventName(@javax.annotation.Nonnull String eventName) {
    this.eventName = eventName;
    return this;
  }

  /**
   * Get eventName
   * @return eventName
   */
  @javax.annotation.Nonnull
  public String getEventName() {
    return eventName;
  }

  public void setEventName(@javax.annotation.Nonnull String eventName) {
    this.eventName = eventName;
  }


  public SalePayload timestamp(@javax.annotation.Nullable OffsetDateTime timestamp) {
    this.timestamp = timestamp;
    return this;
  }

  /**
   * ISO 8601 timestamp.
   * @return timestamp
   */
  @javax.annotation.Nullable
  public OffsetDateTime getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(@javax.annotation.Nullable OffsetDateTime timestamp) {
    this.timestamp = timestamp;
  }


  public SalePayload customerExternalId(@javax.annotation.Nonnull String customerExternalId) {
    this.customerExternalId = customerExternalId;
    return this;
  }

  /**
   * Get customerExternalId
   * @return customerExternalId
   */
  @javax.annotation.Nonnull
  public String getCustomerExternalId() {
    return customerExternalId;
  }

  public void setCustomerExternalId(@javax.annotation.Nonnull String customerExternalId) {
    this.customerExternalId = customerExternalId;
  }


  public SalePayload customerName(@javax.annotation.Nullable String customerName) {
    this.customerName = customerName;
    return this;
  }

  /**
   * Get customerName
   * @return customerName
   */
  @javax.annotation.Nullable
  public String getCustomerName() {
    return customerName;
  }

  public void setCustomerName(@javax.annotation.Nullable String customerName) {
    this.customerName = customerName;
  }


  public SalePayload customerEmail(@javax.annotation.Nullable String customerEmail) {
    this.customerEmail = customerEmail;
    return this;
  }

  /**
   * Get customerEmail
   * @return customerEmail
   */
  @javax.annotation.Nullable
  public String getCustomerEmail() {
    return customerEmail;
  }

  public void setCustomerEmail(@javax.annotation.Nullable String customerEmail) {
    this.customerEmail = customerEmail;
  }


  public SalePayload customerAvatar(@javax.annotation.Nullable URI customerAvatar) {
    this.customerAvatar = customerAvatar;
    return this;
  }

  /**
   * Get customerAvatar
   * @return customerAvatar
   */
  @javax.annotation.Nullable
  public URI getCustomerAvatar() {
    return customerAvatar;
  }

  public void setCustomerAvatar(@javax.annotation.Nullable URI customerAvatar) {
    this.customerAvatar = customerAvatar;
  }


  public SalePayload invoiceId(@javax.annotation.Nonnull String invoiceId) {
    this.invoiceId = invoiceId;
    return this;
  }

  /**
   * Get invoiceId
   * @return invoiceId
   */
  @javax.annotation.Nonnull
  public String getInvoiceId() {
    return invoiceId;
  }

  public void setInvoiceId(@javax.annotation.Nonnull String invoiceId) {
    this.invoiceId = invoiceId;
  }


  public SalePayload amount(@javax.annotation.Nonnull Double amount) {
    this.amount = amount;
    return this;
  }

  /**
   * Amount in cents.
   * @return amount
   */
  @javax.annotation.Nonnull
  public Double getAmount() {
    return amount;
  }

  public void setAmount(@javax.annotation.Nonnull Double amount) {
    this.amount = amount;
  }


  public SalePayload currency(@javax.annotation.Nonnull String currency) {
    this.currency = currency;
    return this;
  }

  /**
   * 3-letter currency code.
   * @return currency
   */
  @javax.annotation.Nonnull
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(@javax.annotation.Nonnull String currency) {
    this.currency = currency;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SalePayload salePayload = (SalePayload) o;
    return Objects.equals(this.clickId, salePayload.clickId) &&
        Objects.equals(this.eventName, salePayload.eventName) &&
        Objects.equals(this.timestamp, salePayload.timestamp) &&
        Objects.equals(this.customerExternalId, salePayload.customerExternalId) &&
        Objects.equals(this.customerName, salePayload.customerName) &&
        Objects.equals(this.customerEmail, salePayload.customerEmail) &&
        Objects.equals(this.customerAvatar, salePayload.customerAvatar) &&
        Objects.equals(this.invoiceId, salePayload.invoiceId) &&
        Objects.equals(this.amount, salePayload.amount) &&
        Objects.equals(this.currency, salePayload.currency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clickId, eventName, timestamp, customerExternalId, customerName, customerEmail, customerAvatar, invoiceId, amount, currency);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SalePayload {\n");
    sb.append("    clickId: ").append(toIndentedString(clickId)).append("\n");
    sb.append("    eventName: ").append(toIndentedString(eventName)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    customerExternalId: ").append(toIndentedString(customerExternalId)).append("\n");
    sb.append("    customerName: ").append(toIndentedString(customerName)).append("\n");
    sb.append("    customerEmail: ").append(toIndentedString(customerEmail)).append("\n");
    sb.append("    customerAvatar: ").append(toIndentedString(customerAvatar)).append("\n");
    sb.append("    invoiceId: ").append(toIndentedString(invoiceId)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("clickId", "eventName", "timestamp", "customerExternalId", "customerName", "customerEmail", "customerAvatar", "invoiceId", "amount", "currency"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("clickId", "eventName", "customerExternalId", "invoiceId", "amount", "currency"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SalePayload
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SalePayload.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in SalePayload is not found in the empty JSON string", SalePayload.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SalePayload.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `SalePayload` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SalePayload.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("clickId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `clickId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("clickId").toString()));
      }
      if (!jsonObj.get("eventName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `eventName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("eventName").toString()));
      }
      if (!jsonObj.get("customerExternalId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `customerExternalId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("customerExternalId").toString()));
      }
      if ((jsonObj.get("customerName") != null && !jsonObj.get("customerName").isJsonNull()) && !jsonObj.get("customerName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `customerName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("customerName").toString()));
      }
      if ((jsonObj.get("customerEmail") != null && !jsonObj.get("customerEmail").isJsonNull()) && !jsonObj.get("customerEmail").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `customerEmail` to be a primitive type in the JSON string but got `%s`", jsonObj.get("customerEmail").toString()));
      }
      if ((jsonObj.get("customerAvatar") != null && !jsonObj.get("customerAvatar").isJsonNull()) && !jsonObj.get("customerAvatar").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `customerAvatar` to be a primitive type in the JSON string but got `%s`", jsonObj.get("customerAvatar").toString()));
      }
      if (!jsonObj.get("invoiceId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `invoiceId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("invoiceId").toString()));
      }
      if (!jsonObj.get("currency").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `currency` to be a primitive type in the JSON string but got `%s`", jsonObj.get("currency").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SalePayload.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SalePayload' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SalePayload> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SalePayload.class));

       return (TypeAdapter<T>) new TypeAdapter<SalePayload>() {
           @Override
           public void write(JsonWriter out, SalePayload value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SalePayload read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SalePayload given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SalePayload
   * @throws IOException if the JSON string is invalid with respect to SalePayload
   */
  public static SalePayload fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SalePayload.class);
  }

  /**
   * Convert an instance of SalePayload to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

