/*
 * CutMeShort CMS API
 * Official API for the CutMeShort CMS platform.  This API allows tracking of leads and sales, including deferred lead attribution. In deferred attribution, the first lead call stores the clickId-to-customerExternalId association using `mode: deferred`. Subsequent lead events should be sent as normal events without `mode`, and the backend resolves the stored association automatically. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cutmeshort.client.api;

import com.cutmeshort.client.exception.ApiException;
import com.cutmeshort.client.model.ErrorResponse;
import com.cutmeshort.client.model.LeadPayload;
import com.cutmeshort.client.model.SalePayload;
import com.cutmeshort.client.model.TrackResponse;
import com.cutmeshort.client.core.Configuration;
import com.cutmeshort.client.auth.ApiKeyAuth;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.DisplayName;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

/**
 * API tests for TrackingApi
 * 
 * These tests verify the core functionality of the CutMeShort Java SDK.
 * Configure the CUTMESHORT_API_KEY environment variable to enable API tests.
 */
public class TrackingApiTest {

    private TrackingApi api;
    private static final String TEST_API_KEY = System.getenv("CUTMESHORT_API_KEY");
    private static final boolean SKIP_API_TESTS = TEST_API_KEY == null || TEST_API_KEY.isEmpty();

    @BeforeEach
    public void setUp() {
        api = new TrackingApi();
        
        // Configure API key if provided
        if (!SKIP_API_TESTS) {
            ApiKeyAuth auth = (ApiKeyAuth) Configuration.getDefaultApiClient()
                .getAuthentication("api_key");
            auth.setApiKey(TEST_API_KEY);
        }
    }

    /**
     * Track a lead event - Basic test
     *
     * Records a lead event with required fields.
     * Requires CUTMESHORT_API_KEY environment variable.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    @DisplayName("Track lead with required fields")
    public void trackLeadTest() throws ApiException {
        if (SKIP_API_TESTS) {
            System.out.println("⚠️ Skipping API test - Set CUTMESHORT_API_KEY environment variable to run");
            return;
        }

        // Create lead payload with required fields
        LeadPayload leadPayload = new LeadPayload()
            .clickId("test_click_" + UUID.randomUUID().toString())
            .eventName("test_lead_event")
            .customerExternalId("test_customer_" + System.currentTimeMillis());

        // Track the lead
        TrackResponse response = api.trackLead(leadPayload);

        // Validate response
        assertNotNull(response, "Response should not be null");
        assertTrue(response.getSuccess(), "Lead tracking should be successful");
        assertNotNull(response.getMessage(), "Response should contain a message");
    }

    /**
     * Track a lead event with all optional fields
     *
     * Tests lead tracking with complete customer information.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    @DisplayName("Track lead with all fields populated")
    public void trackLeadWithAllFieldsTest() throws ApiException {
        if (SKIP_API_TESTS) {
            System.out.println("⚠️ Skipping API test - Set CUTMESHORT_API_KEY environment variable to run");
            return;
        }

        // Create lead payload with all fields
        LeadPayload leadPayload = new LeadPayload()
            .clickId("test_click_full_" + UUID.randomUUID().toString())
            .eventName("lead_signup")
            .customerExternalId("cust_" + System.currentTimeMillis())
            .customerName("John Doe")
            .customerEmail("john@example.com");

        // Track the lead
        TrackResponse response = api.trackLead(leadPayload);

        // Validate response
        assertNotNull(response, "Response should not be null");
        assertTrue(response.getSuccess(), "Lead tracking with all fields should succeed");
        assertNotNull(response.getData(), "Response data should be present");
    }

    /**
     * Track a lead event with deferred attribution mode
     *
     * Tests the deferred attribution pattern for lead events.
     * First call stores the click association, later calls resolve it automatically.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    @DisplayName("Track lead in deferred attribution mode")
    public void trackLeadDeferredAttributionTest() throws ApiException {
        if (SKIP_API_TESTS) {
            System.out.println("⚠️ Skipping API test - Set CUTMESHORT_API_KEY environment variable to run");
            return;
        }

        String baseTestId = UUID.randomUUID().toString();
        
        // First call: Store click association with deferred mode
        LeadPayload deferredLead = new LeadPayload()
            .clickId("deferred_click_" + baseTestId)
            .eventName("page_visit")
            .customerExternalId("deferred_cust_" + System.currentTimeMillis())
            .mode(LeadPayload.ModeEnum.DEFERRED);

        TrackResponse deferredResponse = api.trackLead(deferredLead);
        assertTrue(deferredResponse.getSuccess(), "Deferred lead tracking should succeed");

        // Later: Send normal lead event (without mode)
        LeadPayload normalLead = new LeadPayload()
            .eventName("signup_completed")
            .customerExternalId("deferred_cust_" + System.currentTimeMillis());

        TrackResponse normalResponse = api.trackLead(normalLead);
        assertTrue(normalResponse.getSuccess(), "Normal lead tracking should succeed");
    }

    /**
     * Track a sale event
     *
     * Records a sale or purchase completion event with transaction details.
     * Requires CUTMESHORT_API_KEY environment variable.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    @DisplayName("Track sale event with required fields")
    public void trackSaleTest() throws ApiException {
        if (SKIP_API_TESTS) {
            System.out.println("⚠️ Skipping API test - Set CUTMESHORT_API_KEY environment variable to run");
            return;
        }

        String baseTestId = UUID.randomUUID().toString();
        
        // Create sale payload with required fields
        SalePayload salePayload = new SalePayload()
            .clickId("test_sale_click_" + baseTestId)
            .eventName("purchase_completed")
            .customerExternalId("test_sale_cust_" + System.currentTimeMillis())
            .invoiceId("inv_" + baseTestId)
            .amount(99.99)
            .currency("USD");

        // Track the sale
        TrackResponse response = api.trackSale(salePayload);

        // Validate response
        assertNotNull(response, "Response should not be null");
        assertTrue(response.getSuccess(), "Sale tracking should be successful");
        assertNotNull(response.getMessage(), "Response should contain a message");
    }

    /**
     * Track a sale event with complete details
     *
     * Tests sale tracking with additional transaction information.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    @DisplayName("Track sale event with complete transaction details")
    public void trackSaleWithDetailsTest() throws ApiException {
        if (SKIP_API_TESTS) {
            System.out.println("⚠️ Skipping API test - Set CUTMESHORT_API_KEY environment variable to run");
            return;
        }

        String baseTestId = UUID.randomUUID().toString();
        
        // Create sale payload with full details
        SalePayload salePayload = new SalePayload()
            .clickId("test_sale_details_" + baseTestId)
            .eventName("order_completed")
            .customerExternalId("sale_cust_" + System.currentTimeMillis())
            .invoiceId("inv_" + baseTestId)
            .amount(299.99)
            .currency("USD");

        // Track the sale
        TrackResponse response = api.trackSale(salePayload);

        // Validate response
        assertNotNull(response, "Response should not be null");
        assertTrue(response.getSuccess(), "Sale tracking with details should succeed");
        assertNotNull(response.getData(), "Response data should be present");
    }

    /**
     * Verify API client configuration
     *
     * Tests that the API client is properly configured with correct base path.
     */
    @Test
    @DisplayName("Verify API client configuration")
    public void testApiClientConfiguration() {
        // Verify API client exists
        assertNotNull(api, "TrackingApi should be instantiated");
        
        // Verify base path is configured
        String basePath = Configuration.getDefaultApiClient().getBasePath();
        assertNotNull(basePath, "Base path should be configured");
        assertTrue(basePath.contains("cutmeshort.com"), 
            "Base path should point to CutMeShort API");
    }

    /**
     * Verify API key authentication is configured
     *
     * Tests that API key authentication is available in the configuration.
     */
    @Test
    @DisplayName("Verify API key authentication configuration")
    public void testApiKeyAuthConfiguration() {
        // API client should exist and have authentication mechanism
        assertNotNull(Configuration.getDefaultApiClient(), 
            "API client should be configured");
        
        // Authentication can be retrieved (may be null if not yet initialized)
        Object auth = Configuration.getDefaultApiClient().getAuthentication("api_key");
        // This is optional - authentication is lazily initialized
    }

}
