/*
 * CutMeShort CMS API
 * Official API for the CutMeShort CMS platform.  This API allows tracking of leads and sales, including deferred lead attribution. In deferred attribution, the first lead call stores the clickId-to-customerExternalId association using `mode: deferred`. Subsequent lead events should be sent as normal events without `mode`, and the backend resolves the stored association automatically. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cutmeshort.client.api;

import com.cutmeshort.client.core.ApiCallback;
import com.cutmeshort.client.core.ApiClient;
import com.cutmeshort.client.exception.ApiException;
import com.cutmeshort.client.core.ApiResponse;
import com.cutmeshort.client.util.AppConstants;
import com.cutmeshort.client.core.Configuration;
import com.cutmeshort.client.util.Pair;
import com.cutmeshort.client.request.ProgressRequestBody;
import com.cutmeshort.client.request.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.cutmeshort.client.model.ErrorResponse;
import com.cutmeshort.client.model.LeadPayload;
import com.cutmeshort.client.model.SalePayload;
import com.cutmeshort.client.model.TrackResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TrackingApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public TrackingApi() {
        this(Configuration.getDefaultApiClient());
    }

    public TrackingApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for trackLead
     * @param leadPayload  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Lead tracked successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid payload format </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Invalid or missing API key </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Insufficient permissions </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resource not found </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Resource already exists </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation failed </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> Too many requests </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Server error </td><td>  -  </td></tr>
        <tr><td> 502 </td><td> Gateway error </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> Service unavailable </td><td>  -  </td></tr>
        <tr><td> 504 </td><td> Gateway timeout </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call trackLeadCall(@javax.annotation.Nonnull LeadPayload leadPayload, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = leadPayload;

        // create path and map variables
        String localVarPath = AppConstants.ENDPOINT_TRACK_LEAD;

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { AppConstants.AUTH_SCHEME_API_KEY };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call trackLeadValidateBeforeCall(@javax.annotation.Nonnull LeadPayload leadPayload, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'leadPayload' is set
        if (leadPayload == null) {
            throw new ApiException("Missing the required parameter 'leadPayload' when calling trackLead(Async)");
        }

        return trackLeadCall(leadPayload, _callback);

    }

    /**
     * Track a lead event
     * Records a lead event.  Standard mode: - Send &#x60;clickId&#x60;, &#x60;eventName&#x60;, and &#x60;customerExternalId&#x60;.  Deferred attribution mode: - First call: send &#x60;clickId&#x60;, &#x60;eventName&#x60;, &#x60;customerExternalId&#x60;, and &#x60;mode: deferred&#x60;   to store the click association. - Later calls: send normal lead events with &#x60;eventName&#x60; and &#x60;customerExternalId&#x60;   only, without &#x60;mode&#x60;. The backend resolves the previously stored association. 
     * @param leadPayload  (required)
     * @return TrackResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Lead tracked successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid payload format </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Invalid or missing API key </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Insufficient permissions </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resource not found </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Resource already exists </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation failed </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> Too many requests </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Server error </td><td>  -  </td></tr>
        <tr><td> 502 </td><td> Gateway error </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> Service unavailable </td><td>  -  </td></tr>
        <tr><td> 504 </td><td> Gateway timeout </td><td>  -  </td></tr>
     </table>
     */
    public TrackResponse trackLead(@javax.annotation.Nonnull LeadPayload leadPayload) throws ApiException {
        ApiResponse<TrackResponse> localVarResp = trackLeadWithHttpInfo(leadPayload);
        return localVarResp.getData();
    }

    /**
     * Track a lead event
     * Records a lead event.  Standard mode: - Send &#x60;clickId&#x60;, &#x60;eventName&#x60;, and &#x60;customerExternalId&#x60;.  Deferred attribution mode: - First call: send &#x60;clickId&#x60;, &#x60;eventName&#x60;, &#x60;customerExternalId&#x60;, and &#x60;mode: deferred&#x60;   to store the click association. - Later calls: send normal lead events with &#x60;eventName&#x60; and &#x60;customerExternalId&#x60;   only, without &#x60;mode&#x60;. The backend resolves the previously stored association. 
     * @param leadPayload  (required)
     * @return ApiResponse&lt;TrackResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Lead tracked successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid payload format </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Invalid or missing API key </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Insufficient permissions </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resource not found </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Resource already exists </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation failed </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> Too many requests </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Server error </td><td>  -  </td></tr>
        <tr><td> 502 </td><td> Gateway error </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> Service unavailable </td><td>  -  </td></tr>
        <tr><td> 504 </td><td> Gateway timeout </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<TrackResponse> trackLeadWithHttpInfo(@javax.annotation.Nonnull LeadPayload leadPayload) throws ApiException {
        okhttp3.Call localVarCall = trackLeadValidateBeforeCall(leadPayload, null);
        Type localVarReturnType = new TypeToken<TrackResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Track a lead event (asynchronously)
     * Records a lead event.  Standard mode: - Send &#x60;clickId&#x60;, &#x60;eventName&#x60;, and &#x60;customerExternalId&#x60;.  Deferred attribution mode: - First call: send &#x60;clickId&#x60;, &#x60;eventName&#x60;, &#x60;customerExternalId&#x60;, and &#x60;mode: deferred&#x60;   to store the click association. - Later calls: send normal lead events with &#x60;eventName&#x60; and &#x60;customerExternalId&#x60;   only, without &#x60;mode&#x60;. The backend resolves the previously stored association. 
     * @param leadPayload  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Lead tracked successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid payload format </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Invalid or missing API key </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Insufficient permissions </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resource not found </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Resource already exists </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation failed </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> Too many requests </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Server error </td><td>  -  </td></tr>
        <tr><td> 502 </td><td> Gateway error </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> Service unavailable </td><td>  -  </td></tr>
        <tr><td> 504 </td><td> Gateway timeout </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call trackLeadAsync(@javax.annotation.Nonnull LeadPayload leadPayload, final ApiCallback<TrackResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = trackLeadValidateBeforeCall(leadPayload, _callback);
        Type localVarReturnType = new TypeToken<TrackResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for trackSale
     * @param salePayload  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Sale tracked successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid payload format </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Invalid or missing API key </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Insufficient permissions </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resource not found </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Resource already exists </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation failed </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> Too many requests </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Server error </td><td>  -  </td></tr>
        <tr><td> 502 </td><td> Gateway error </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> Service unavailable </td><td>  -  </td></tr>
        <tr><td> 504 </td><td> Gateway timeout </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call trackSaleCall(@javax.annotation.Nonnull SalePayload salePayload, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = salePayload;

        // create path and map variables
        String localVarPath = AppConstants.ENDPOINT_TRACK_SALE;

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { AppConstants.AUTH_SCHEME_API_KEY };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call trackSaleValidateBeforeCall(@javax.annotation.Nonnull SalePayload salePayload, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'salePayload' is set
        if (salePayload == null) {
            throw new ApiException("Missing the required parameter 'salePayload' when calling trackSale(Async)");
        }

        return trackSaleCall(salePayload, _callback);

    }

    /**
     * Track a sale event
     * Records a sale or purchase completion event.
     * @param salePayload  (required)
     * @return TrackResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Sale tracked successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid payload format </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Invalid or missing API key </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Insufficient permissions </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resource not found </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Resource already exists </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation failed </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> Too many requests </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Server error </td><td>  -  </td></tr>
        <tr><td> 502 </td><td> Gateway error </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> Service unavailable </td><td>  -  </td></tr>
        <tr><td> 504 </td><td> Gateway timeout </td><td>  -  </td></tr>
     </table>
     */
    public TrackResponse trackSale(@javax.annotation.Nonnull SalePayload salePayload) throws ApiException {
        ApiResponse<TrackResponse> localVarResp = trackSaleWithHttpInfo(salePayload);
        return localVarResp.getData();
    }

    /**
     * Track a sale event
     * Records a sale or purchase completion event.
     * @param salePayload  (required)
     * @return ApiResponse&lt;TrackResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Sale tracked successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid payload format </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Invalid or missing API key </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Insufficient permissions </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resource not found </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Resource already exists </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation failed </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> Too many requests </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Server error </td><td>  -  </td></tr>
        <tr><td> 502 </td><td> Gateway error </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> Service unavailable </td><td>  -  </td></tr>
        <tr><td> 504 </td><td> Gateway timeout </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<TrackResponse> trackSaleWithHttpInfo(@javax.annotation.Nonnull SalePayload salePayload) throws ApiException {
        okhttp3.Call localVarCall = trackSaleValidateBeforeCall(salePayload, null);
        Type localVarReturnType = new TypeToken<TrackResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Track a sale event (asynchronously)
     * Records a sale or purchase completion event.
     * @param salePayload  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Sale tracked successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid payload format </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Invalid or missing API key </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Insufficient permissions </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resource not found </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Resource already exists </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation failed </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> Too many requests </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Server error </td><td>  -  </td></tr>
        <tr><td> 502 </td><td> Gateway error </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> Service unavailable </td><td>  -  </td></tr>
        <tr><td> 504 </td><td> Gateway timeout </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call trackSaleAsync(@javax.annotation.Nonnull SalePayload salePayload, final ApiCallback<TrackResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = trackSaleValidateBeforeCall(salePayload, _callback);
        Type localVarReturnType = new TypeToken<TrackResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
