/*
 * CutMeShort CMS API
 * Official API for the CutMeShort CMS platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.cutmeshort.client.util;

/**
 * Application Constants
 *
 * This class contains all hardcoded constants used throughout the SDK.
 * Centralizing constants here ensures consistency and makes it easy to update
 * configuration without modifying multiple files.
 *
 * <h2>Environment Variables</h2>
 * Most configuration can be overridden via environment variables:
 * <ul>
 *   <li>CUTMESHORT_API_URL - Base API URL (default: https://www.cutmeshort.com)</li>
 *   <li>CUTMESHORT_API_KEY - API key for authentication (required for production)</li>
 *   <li>CUTMESHORT_ENVIRONMENT - Environment: development, staging, production</li>
 *   <li>CUTMESHORT_CONNECT_TIMEOUT_SECONDS - Connection timeout in seconds (default: 30)</li>
 *   <li>CUTMESHORT_READ_TIMEOUT_SECONDS - Read timeout in seconds (default: 60)</li>
 *   <li>CUTMESHORT_WRITE_TIMEOUT_SECONDS - Write timeout in seconds (default: 60)</li>
 *   <li>CUTMESHORT_DEBUG_MODE - Enable debug logging (default: false)</li>
 *   <li>CUTMESHORT_VERIFY_SSL - Enable SSL verification (default: true in production)</li>
 * </ul>
 *
 * <h2>Security Notes</h2>
 * - API keys should NEVER be hardcoded in source code
 * - Always use environment variables or secure vaults for API keys
 * - Debug mode should NOT be enabled in production
 * - SSL verification must be enabled in production environments
 *
 * @version 1.0.0
 */
public final class AppConstants {

    // Private constructor to prevent instantiation
    private AppConstants() {
        throw new AssertionError("Cannot instantiate AppConstants");
    }

    // ============================================================================
    // API CONFIGURATION
    // ============================================================================

    /**
     * SDK Version
     */
    public static final String SDK_VERSION = "1.0.0";

    /**
     * Default production API base URL
     * Can be overridden with CUTMESHORT_API_URL environment variable
     */
    public static final String DEFAULT_API_BASE_URL = "https://www.cutmeshort.com";

    /**
     * Environment variable for API base URL
     */
    public static final String ENV_API_URL = "CUTMESHORT_API_URL";

    /**
     * Environment variable for API key (SECURE: Store in vault, not in code)
     */
    public static final String ENV_API_KEY = "CUTMESHORT_API_KEY";

    /**
     * Environment variable for environment type
     */
    public static final String ENV_ENVIRONMENT = "CUTMESHORT_ENVIRONMENT";

    // ============================================================================
    // AUTHENTICATION CONFIGURATION
    // ============================================================================

    /**
     * Authentication type for API key
     */
    @Deprecated
    public static final String AUTH_TYPE_HEADER = "header";

    /**
     * API key header name
     * WARNING: This header contains sensitive authentication data.
     *          Never log or expose this value in debug output.
     */
    public static final String API_KEY_HEADER_NAME = "Authorization";

    /**
     * Authentication scheme name used internally
     */
    public static final String AUTH_SCHEME_API_KEY = "ApiKeyAuth";

    /**
     * Authentication location (header, query, cookie)
     */
    public static final String AUTH_LOCATION_HEADER = "header";

    // ============================================================================
    // HTTP HEADERS
    // ============================================================================

    /**
     * Content-Type header name
     */
    public static final String HEADER_CONTENT_TYPE = "Content-Type";

    /**
     * Content-Type for JSON
     */
    public static final String CONTENT_TYPE_JSON = "application/json";

    /**
     * Accept header name
     */
    public static final String HEADER_ACCEPT = "Accept";

    /**
     * User-Agent header name
     */
    public static final String HEADER_USER_AGENT = "User-Agent";

    /**
     * Default User-Agent string
     * Can be customized by calling ApiClient.setUserAgent(String)
     */
    public static final String DEFAULT_USER_AGENT = "CutMeShort-SDK/1.0.0 (Java; OpenAPI-Generator)";

    /**
     * Authorization header name
     */
    public static final String HEADER_AUTHORIZATION = "Authorization";

    /**
     * Retry-After header name
     */
    public static final String HEADER_RETRY_AFTER = "Retry-After";

    /**
     * Content-Disposition header name
     */
    public static final String HEADER_CONTENT_DISPOSITION = "Content-Disposition";

    /**
     * Content-Encoding header name
     */
    public static final String HEADER_CONTENT_ENCODING = "Content-Encoding";

    /**
     * Gzip encoding
     */
    public static final String ENCODING_GZIP = "gzip";

    // ============================================================================
    // API ENDPOINTS
    // ============================================================================

    /**
     * Track lead endpoint path
     */
    public static final String ENDPOINT_TRACK_LEAD = "/track/lead";

    /**
     * Track sale endpoint path
     */
    public static final String ENDPOINT_TRACK_SALE = "/track/sale";

    // ============================================================================
    // HTTP METHOD CONSTANTS
    // ============================================================================

    /**
     * HTTP POST method
     */
    public static final String HTTP_METHOD_POST = "POST";

    /**
     * HTTP GET method
     */
    public static final String HTTP_METHOD_GET = "GET";

    /**
     * HTTP PUT method
     */
    public static final String HTTP_METHOD_PUT = "PUT";

    /**
     * HTTP DELETE method
     */
    public static final String HTTP_METHOD_DELETE = "DELETE";

    /**
     * HTTP PATCH method
     */
    public static final String HTTP_METHOD_PATCH = "PATCH";

    // ============================================================================
    // TIMEOUT CONFIGURATION (in milliseconds)
    // ============================================================================

    /**
     * Default connection timeout in seconds
     * Can be overridden with CUTMESHORT_CONNECT_TIMEOUT_SECONDS
     */
    public static final int DEFAULT_CONNECT_TIMEOUT_SECONDS = 30;

    /**
     * Default read timeout in seconds
     * Can be overridden with CUTMESHORT_READ_TIMEOUT_SECONDS
     */
    public static final int DEFAULT_READ_TIMEOUT_SECONDS = 60;

    /**
     * Default write timeout in seconds
     * Can be overridden with CUTMESHORT_WRITE_TIMEOUT_SECONDS
     */
    public static final int DEFAULT_WRITE_TIMEOUT_SECONDS = 60;

    /**
     * Environment variable for connect timeout
     */
    public static final String ENV_CONNECT_TIMEOUT_SECONDS = "CUTMESHORT_CONNECT_TIMEOUT_SECONDS";

    /**
     * Environment variable for read timeout
     */
    public static final String ENV_READ_TIMEOUT_SECONDS = "CUTMESHORT_READ_TIMEOUT_SECONDS";

    /**
     * Environment variable for write timeout
     */
    public static final String ENV_WRITE_TIMEOUT_SECONDS = "CUTMESHORT_WRITE_TIMEOUT_SECONDS";

    // ============================================================================
    // RETRY AND BACKOFF CONFIGURATION
    // ============================================================================

    /**
     * Maximum number of retry attempts for failed requests
     */
    public static final int MAX_RETRY_ATTEMPTS = 3;

    /**
     * Initial backoff delay in milliseconds
     * Follows exponential backoff: 100ms, 200ms, 400ms, 800ms, etc.
     */
    public static final long INITIAL_BACKOFF_MS = 100;

    /**
     * Maximum backoff delay in milliseconds (32 seconds)
     * Prevents excessive delays on repeated failures
     */
    public static final long MAX_BACKOFF_MS = 32000;

    /**
     * Backoff multiplier for exponential backoff (2.0x)
     */
    public static final double BACKOFF_MULTIPLIER = 2.0;

    // ============================================================================
    // HTTP STATUS CODES
    // ============================================================================

    /**
     * HTTP 200 OK
     */
    public static final int STATUS_OK = 200;

    /**
     * HTTP 201 Created
     */
    public static final int STATUS_CREATED = 201;

    /**
     * HTTP 204 No Content
     */
    public static final int STATUS_NO_CONTENT = 204;

    /**
     * HTTP 400 Bad Request
     */
    public static final int STATUS_BAD_REQUEST = 400;

    /**
     * HTTP 401 Unauthorized - Invalid or missing authentication
     */
    public static final int STATUS_UNAUTHORIZED = 401;

    /**
     * HTTP 403 Forbidden - Insufficient permissions
     */
    public static final int STATUS_FORBIDDEN = 403;

    /**
     * HTTP 404 Not Found
     */
    public static final int STATUS_NOT_FOUND = 404;

    /**
     * HTTP 409 Conflict - Resource already exists
     */
    public static final int STATUS_CONFLICT = 409;

    /**
     * HTTP 422 Unprocessable Entity - Validation failed
     */
    public static final int STATUS_UNPROCESSABLE_ENTITY = 422;

    /**
     * HTTP 429 Too Many Requests - Rate limit exceeded
     */
    public static final int STATUS_RATE_LIMIT = 429;

    /**
     * HTTP 500 Internal Server Error
     */
    public static final int STATUS_SERVER_ERROR = 500;

    /**
     * HTTP 502 Bad Gateway
     */
    public static final int STATUS_BAD_GATEWAY = 502;

    /**
     * HTTP 503 Service Unavailable
     */
    public static final int STATUS_SERVICE_UNAVAILABLE = 503;

    /**
     * HTTP 504 Gateway Timeout
     */
    public static final int STATUS_GATEWAY_TIMEOUT = 504;

    // ============================================================================
    // CONNECTION POOL CONFIGURATION
    // ============================================================================

    /**
     * Maximum number of idle connections in the connection pool
     */
    public static final int CONNECTION_POOL_MAX_IDLE = 10;

    /**
     * Keep-alive duration for connections in minutes
     */
    public static final int CONNECTION_POOL_KEEP_ALIVE_MINUTES = 5;

    // ============================================================================
    // SECURITY CONFIGURATION
    // ============================================================================

    /**
     * Environment variable to enable/disable debug mode
     */
    public static final String ENV_DEBUG_MODE = "CUTMESHORT_DEBUG_MODE";

    /**
     * Environment variable to enable/disable SSL verification
     * WARNING: Do NOT disable in production
     */
    public static final String ENV_VERIFY_SSL = "CUTMESHORT_VERIFY_SSL";

    /**
     * Default SSL verification setting - ALWAYS enabled in production
     */
    public static final boolean DEFAULT_VERIFY_SSL = true;

    /**
     * SSL/TLS context algorithm
     */
    public static final String SSL_CONTEXT_ALGORITHM = "TLS";

    /**
     * Minimum TLS version for production
     */
    public static final String PRODUCTION_TLS_VERSION = "TLSv1.2";

    // ============================================================================
    // ENVIRONMENT NAMES
    // ============================================================================

    /**
     * Development environment - Relaxed security, debug logging enabled
     */
    public static final String ENV_DEVELOPMENT = "development";

    /**
     * Staging environment - Production-like, security checks enabled
     */
    public static final String ENV_STAGING = "staging";

    /**
     * Production environment - Strict security, no debug logging
     */
    public static final String ENV_PRODUCTION = "production";

    // ============================================================================
    // LOGGING AND DEBUG CONSTANTS
    // ============================================================================

    /**
     * Sensitive headers that should be redacted from logs
     * These headers contain authentication or sensitive data
     */
    public static final String[] SENSITIVE_HEADERS = {
        "x-api-key",
        "authorization",
        "x-api-token",
        "x-auth-token",
        "api-key",
        "api-secret",
        "x-secret",
        "secret",
        "password",
        "token",
        "auth",
        "bearer",
        "cookie",
        "set-cookie"
    };

    /**
     * Redaction mask for sensitive data in logs
     */
    public static final String REDACTION_MASK = "[REDACTED]";

    /**
     * Email address redaction mask
     */
    public static final String EMAIL_REDACTION_MASK = "[email@redacted.com]";

    /**
     * Phone number redaction mask
     */
    public static final String PHONE_REDACTION_MASK = "[REDACTED_PHONE]";

    // ============================================================================
    // VALIDATION CONSTANTS
    // ============================================================================

    /**
     * Maximum length for clickId field
     */
    public static final int MAX_CLICK_ID_LENGTH = 255;

    /**
     * Maximum length for eventName field
     */
    public static final int MAX_EVENT_NAME_LENGTH = 100;

    /**
     * Maximum length for customerExternalId field
     */
    public static final int MAX_CUSTOMER_EXTERNAL_ID_LENGTH = 255;

    /**
     * Maximum length for customerName field
     */
    public static final int MAX_CUSTOMER_NAME_LENGTH = 255;

    /**
     * Maximum length for customerEmail field
     */
    public static final int MAX_CUSTOMER_EMAIL_LENGTH = 255;

    /**
     * Minimum length for eventName field
     */
    public static final int MIN_EVENT_NAME_LENGTH = 1;

    /**
     * Deferred mode value
     */
    public static final String DEFERRED_MODE = "deferred";

    // ============================================================================
    // ERROR MESSAGES
    // ============================================================================

    /**
     * Error message when API key is not configured
     */
    public static final String ERROR_API_KEY_NOT_CONFIGURED =
        "API_KEY environment variable is not set. " +
        "Set " + ENV_API_KEY + " environment variable with your API credentials.";

    /**
     * Error message when API URL is invalid
     */
    public static final String ERROR_INVALID_API_URL =
        "Invalid API URL. Must start with https:// in production mode.";

    /**
     * Error message when trying to disable SSL in production
     */
    public static final String ERROR_SSL_DISABLED_IN_PRODUCTION =
        "SSL verification cannot be disabled in production mode. " +
        "Set CUTMESHORT_ENVIRONMENT=development to allow disabling SSL.";

    /**
     * Error message for missing required parameter
     */
    public static final String ERROR_REQUIRED_PARAMETER_MISSING =
        "Missing required parameter: ";

    /**
     * Error message for invalid input
     */
    public static final String ERROR_INVALID_INPUT =
        "Invalid input validation failed: ";

    // ============================================================================
    // UTILITY METHODS
    // ============================================================================

    /**
     * Get the API key from environment variables with security considerations
     *
     * @return API key from environment, or null if not set
     * @throws IllegalStateException if required in production and not set
     */
    public static String getApiKey() {
        String apiKey = System.getenv(ENV_API_KEY);
        String environment = System.getenv(ENV_ENVIRONMENT);

        if (apiKey == null && ENV_PRODUCTION.equals(environment)) {
            throw new IllegalStateException(ERROR_API_KEY_NOT_CONFIGURED);
        }

        return apiKey;
    }

    /**
     * Get the API base URL from environment variables with fallback to default
     *
     * @return API base URL
     */
    public static String getApiBaseUrl() {
        String url = System.getenv(ENV_API_URL);
        if (url != null && !url.isEmpty()) {
            return url;
        }
        return DEFAULT_API_BASE_URL;
    }

    /**
     * Get connection timeout from environment or use default
     *
     * @return timeout in seconds
     */
    public static int getConnectTimeout() {
        return getIntFromEnv(ENV_CONNECT_TIMEOUT_SECONDS, DEFAULT_CONNECT_TIMEOUT_SECONDS);
    }

    /**
     * Get read timeout from environment or use default
     *
     * @return timeout in seconds
     */
    public static int getReadTimeout() {
        return getIntFromEnv(ENV_READ_TIMEOUT_SECONDS, DEFAULT_READ_TIMEOUT_SECONDS);
    }

    /**
     * Get write timeout from environment or use default
     *
     * @return timeout in seconds
     */
    public static int getWriteTimeout() {
        return getIntFromEnv(ENV_WRITE_TIMEOUT_SECONDS, DEFAULT_WRITE_TIMEOUT_SECONDS);
    }

    /**
     * Check if debug mode is enabled
     *
     * @return true if debug mode is enabled
     */
    public static boolean isDebugMode() {
        String debug = System.getenv(ENV_DEBUG_MODE);
        return "true".equalsIgnoreCase(debug) || "1".equals(debug);
    }

    /**
     * Check if SSL verification is enabled
     *
     * @return true if SSL verification is enabled (default: true)
     */
    public static boolean isVerifySSL() {
        String verify = System.getenv(ENV_VERIFY_SSL);
        if (verify == null || verify.isEmpty()) {
            return DEFAULT_VERIFY_SSL;
        }
        return "true".equalsIgnoreCase(verify) || "1".equals(verify);
    }

    /**
     * Get current environment type
     *
     * @return environment name (development, staging, production)
     */
    public static String getEnvironment() {
        String env = System.getenv(ENV_ENVIRONMENT);
        return env != null ? env : ENV_DEVELOPMENT;
    }

    /**
     * Check if running in production environment
     *
     * @return true if environment is production
     */
    public static boolean isProduction() {
        return ENV_PRODUCTION.equals(getEnvironment());
    }

    /**
     * Check if running in development environment
     *
     * @return true if environment is development
     */
    public static boolean isDevelopment() {
        return ENV_DEVELOPMENT.equals(getEnvironment());
    }

    /**
     * Check if running in staging environment
     *
     * @return true if environment is staging
     */
    public static boolean isStaging() {
        return ENV_STAGING.equals(getEnvironment());
    }

    // ============================================================================
    // PRIVATE HELPER METHODS
    // ============================================================================

    /**
     * Get integer value from environment variable with fallback to default
     *
     * @param envVariable environment variable name
     * @param defaultValue default value if not set or invalid
     * @return integer value
     */
    private static int getIntFromEnv(String envVariable, int defaultValue) {
        String value = System.getenv(envVariable);
        if (value != null && !value.isEmpty()) {
            try {
                return Integer.parseInt(value);
            } catch (NumberFormatException e) {
                // Ignore and use default
            }
        }
        return defaultValue;
    }
}
